use std::collections::BTreeSet;
use std::io::{BufRead, BufReader, Read, Write};
use std::process::{Command, Stdio};
use std::time::Instant;

use tree_sitter::{Node, Parser};

#[derive(Clone, Copy, PartialEq)]
enum Lang {
    Rust,
    Ts,
    Tsx,
}

const SKIP_DIRS: &[&str] = &[
    ".git", "node_modules", "vendor", "build", ".build", "dist", "target", "__pycache__", ".venv",
    "venv", "DerivedData", "Pods", "coverage", ".next", "out", "fixtures",
];
const TEST_DIRS: &[&str] = &["tests", "test", "spec", "__tests__"];
const TEST_PREFIXES: &[&str] = &["test_", "spec_"];
const TEST_SUFFIXES: &[&str] = &["_test", "_spec", ".test", ".spec", "Test", "Tests"];
const ECMASCRIPT_FUNCTIONS: &[&str] = &[
    "function_declaration",
    "function_expression",
    "generator_function",
    "generator_function_declaration",
    "arrow_function",
    "method_definition",
];
const GENERATED_MARKS: &[&str] = &[
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "code generated by",
];

struct Row {
    path: String,
    lang: &'static str,
    test: bool,
    generated: bool,
    error: bool,
    lines: usize,
    code: usize,
    items: usize,
    functions: usize,
    named: usize,
    production: usize,
    longest: usize,
}

fn lang_of(path: &str) -> Option<Lang> {
    let name = path.rsplit('/').next().unwrap_or(path);
    if name.ends_with(".d.ts") {
        return None;
    }
    if name.ends_with(".rs") {
        Some(Lang::Rust)
    } else if name.ends_with(".tsx") {
        Some(Lang::Tsx)
    } else if [".ts", ".mts", ".cts"].iter().any(|ext| name.ends_with(ext)) {
        Some(Lang::Ts)
    } else {
        None
    }
}

fn in_scope(path: &str) -> bool {
    let mut segments: Vec<&str> = path.split('/').collect();
    segments.pop();
    lang_of(path).is_some()
        && !segments
            .iter()
            .any(|segment| SKIP_DIRS.contains(segment) || segment.starts_with('.'))
}

fn test_file(path: &str) -> bool {
    let mut segments: Vec<&str> = path.split('/').collect();
    let name = segments.pop().unwrap_or("");
    let stem = name.split('.').next().unwrap_or(name);
    let full_stem = name.rsplit_once('.').map_or(name, |(stem, _)| stem);
    segments.iter().any(|segment| TEST_DIRS.contains(segment))
        || TEST_PREFIXES.iter().any(|prefix| stem.starts_with(prefix))
        || TEST_SUFFIXES
            .iter()
            .any(|suffix| full_stem.ends_with(suffix) || stem.ends_with(suffix))
}

fn generated(src: &[u8]) -> bool {
    let head: String = String::from_utf8_lossy(&src[..src.len().min(2048)])
        .lines()
        .take(10)
        .collect::<Vec<_>>()
        .join("\n")
        .to_lowercase();
    GENERATED_MARKS.iter().any(|mark| head.contains(mark))
}

fn parser(lang: Lang) -> Parser {
    let mut parser = Parser::new();
    let grammar: tree_sitter::Language = match lang {
        Lang::Rust => tree_sitter_rust::LANGUAGE.into(),
        Lang::Ts => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
        Lang::Tsx => tree_sitter_typescript::LANGUAGE_TSX.into(),
    };
    parser.set_language(&grammar).expect("grammar");
    parser
}

fn comment(kind: &str) -> bool {
    matches!(kind, "comment" | "line_comment" | "block_comment")
}

fn text<'a>(node: Node, src: &'a [u8]) -> &'a str {
    node.utf8_text(src).unwrap_or("")
}

fn attributes_mention(node: Node, src: &[u8], needle: &str) -> bool {
    let mut previous = node.prev_named_sibling();
    while let Some(sibling) = previous {
        match sibling.kind() {
            "attribute_item" => {
                if text(sibling, src).contains(needle) {
                    return true;
                }
            }
            kind if comment(kind) => {}
            _ => break,
        }
        previous = sibling.prev_named_sibling();
    }
    false
}

fn rust_test_function(node: Node, src: &[u8]) -> bool {
    let mut previous = node.prev_named_sibling();
    while let Some(sibling) = previous {
        match sibling.kind() {
            "attribute_item" => {
                let body = text(sibling, src);
                let inner = body.trim_start_matches("#[").trim_end_matches(']');
                let path = inner.split('(').next().unwrap_or("").trim();
                if path == "test" || path.ends_with("::test") || path == "rstest" || path == "test_case" {
                    return true;
                }
            }
            kind if comment(kind) => {}
            _ => break,
        }
        previous = sibling.prev_named_sibling();
    }
    false
}

fn named_ecmascript(node: Node) -> bool {
    match node.kind() {
        "function_declaration" | "generator_function_declaration" | "method_definition" => true,
        _ => node.parent().is_some_and(|parent| {
            matches!(
                parent.kind(),
                "variable_declarator" | "public_field_definition" | "field_definition"
            )
        }),
    }
}

struct Walk<'a> {
    lang: Lang,
    src: &'a [u8],
    rows: BTreeSet<usize>,
    functions: usize,
    named: usize,
    production: usize,
    longest: usize,
}

impl Walk<'_> {
    fn visit(&mut self, node: Node, in_test: bool) {
        let kind = node.kind();
        if comment(kind) {
            return;
        }
        if node.child_count() == 0 {
            for row in node.start_position().row..=node.end_position().row {
                self.rows.insert(row);
            }
            return;
        }
        let mut in_test = in_test;
        match self.lang {
            Lang::Rust => {
                if kind == "mod_item" && attributes_mention(node, self.src, "cfg(test)") {
                    in_test = true;
                }
                if kind == "function_item" {
                    self.count(node, true, in_test || rust_test_function(node, self.src));
                }
            }
            Lang::Ts | Lang::Tsx => {
                if ECMASCRIPT_FUNCTIONS.contains(&kind) {
                    self.count(node, named_ecmascript(node), in_test);
                }
            }
        }
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            self.visit(child, in_test);
        }
    }

    fn count(&mut self, node: Node, named: bool, test: bool) {
        self.functions += 1;
        let span = node.end_position().row - node.start_position().row + 1;
        if named {
            self.named += 1;
            if !test {
                self.production += 1;
            }
        }
        if !test {
            self.longest = self.longest.max(span);
        }
    }
}

fn items(lang: Lang, root: Node, src: &[u8]) -> usize {
    let mut cursor = root.walk();
    root.named_children(&mut cursor)
        .filter(|child| match lang {
            Lang::Rust => match child.kind() {
                "use_declaration" | "attribute_item" | "inner_attribute_item"
                | "extern_crate_declaration" | "line_comment" | "block_comment" | "empty_statement" => false,
                "mod_item" => child.child_by_field_name("body").is_some(),
                _ => true,
            },
            Lang::Ts | Lang::Tsx => match child.kind() {
                "import_statement" | "comment" | "empty_statement" => false,
                "export_statement" => {
                    child.child_by_field_name("declaration").is_some()
                        || child.child_by_field_name("value").is_some()
                        || !text(*child, src).contains(" from ")
                            && !text(*child, src).trim_start().starts_with("export {")
                            && !text(*child, src).trim_start().starts_with("export *")
                }
                _ => true,
            },
        })
        .count()
}

fn measure(path: &str, src: &[u8], parsers: &mut [Parser; 3]) -> Option<Row> {
    let lang = lang_of(path)?;
    let parser = &mut parsers[lang as usize];
    let tree = parser.parse(src, None)?;
    let root = tree.root_node();
    let mut walk = Walk {
        lang,
        src,
        rows: BTreeSet::new(),
        functions: 0,
        named: 0,
        production: 0,
        longest: 0,
    };
    let test = test_file(path);
    walk.visit(root, test);
    let lines = if src.is_empty() {
        0
    } else {
        src.iter().filter(|byte| **byte == b'\n').count() + usize::from(src.last() != Some(&b'\n'))
    };
    Some(Row {
        path: path.to_string(),
        lang: match lang {
            Lang::Rust => "rust",
            Lang::Ts | Lang::Tsx => "ts",
        },
        test,
        generated: generated(src),
        error: root.has_error(),
        lines,
        code: walk.rows.len(),
        items: items(lang, root, src),
        functions: walk.functions,
        named: walk.named,
        production: walk.production,
        longest: walk.longest,
    })
}

fn git(repo: &str, args: &[&str]) -> String {
    let output = Command::new("git")
        .arg("-C")
        .arg(repo)
        .args(args)
        .output()
        .expect("git");
    String::from_utf8_lossy(&output.stdout).into_owned()
}

fn print_header(out: &mut impl Write) {
    writeln!(
        out,
        "path\tlang\ttest\tgenerated\terror\tlines\tcode\titems\tfunctions\tnamed\tproduction\tlongest"
    )
    .unwrap();
}

fn print_row(out: &mut impl Write, row: &Row) {
    writeln!(
        out,
        "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",
        row.path,
        row.lang,
        u8::from(row.test),
        u8::from(row.generated),
        u8::from(row.error),
        row.lines,
        row.code,
        row.items,
        row.functions,
        row.named,
        row.production,
        row.longest
    )
    .unwrap();
}

/// Reads every in-scope blob of `rev` through one `git cat-file --batch`, so a scan of a
/// commit and of a working tree measure the same bytes.
fn scan(repo: &str, rev: &str, only: Option<&BTreeSet<String>>) -> Vec<Row> {
    let listing = git(repo, &["ls-tree", "-r", "--full-tree", rev]);
    let mut wanted = Vec::new();
    for line in listing.lines() {
        let Some((meta, path)) = line.split_once('\t') else { continue };
        let mut parts = meta.split_whitespace();
        let (_mode, kind, oid) = (parts.next(), parts.next(), parts.next());
        if kind != Some("blob") || !in_scope(path) {
            continue;
        }
        if only.is_some_and(|set| !set.contains(path)) {
            continue;
        }
        wanted.push((oid.unwrap_or("").to_string(), path.to_string()));
    }
    let mut child = Command::new("git")
        .arg("-C")
        .arg(repo)
        .args(["cat-file", "--batch"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("cat-file");
    let mut stdin = child.stdin.take().unwrap();
    let oids: Vec<String> = wanted.iter().map(|(oid, _)| oid.clone()).collect();
    let feeder = std::thread::spawn(move || {
        for oid in oids {
            writeln!(stdin, "{oid}").unwrap();
        }
    });
    let mut reader = BufReader::new(child.stdout.take().unwrap());
    let mut parsers = [parser(Lang::Rust), parser(Lang::Ts), parser(Lang::Tsx)];
    let mut rows = Vec::new();
    for (_, path) in &wanted {
        let mut header = String::new();
        reader.read_line(&mut header).unwrap();
        let size: usize = header.split_whitespace().nth(2).and_then(|s| s.parse().ok()).unwrap_or(0);
        let mut body = vec![0; size + 1];
        reader.read_exact(&mut body).unwrap();
        body.pop();
        if let Some(row) = measure(path, &body, &mut parsers) {
            rows.push(row);
        }
    }
    feeder.join().unwrap();
    child.wait().unwrap();
    rows
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    match args.get(1).map(String::as_str) {
        Some("scan") => {
            let repo = &args[2];
            let rev = args.get(3).map_or("HEAD", String::as_str);
            print_header(&mut out);
            for row in scan(repo, rev, None) {
                print_row(&mut out, &row);
            }
        }
        Some("change") => {
            let (repo, base, head) = (&args[2], &args[3], &args[4]);
            let names = git(repo, &["diff", "--no-renames", "--name-only", base, head]);
            let changed: BTreeSet<String> = names.lines().map(str::to_string).collect();
            writeln!(out, "side\t{}", "path\tlang\ttest\tgenerated\terror\tlines\tcode\titems\tfunctions\tnamed\tproduction\tlongest").unwrap();
            for (side, rev) in [("base", base), ("head", head)] {
                for row in scan(repo, rev, Some(&changed)) {
                    write!(out, "{side}\t").unwrap();
                    print_row(&mut out, &row);
                }
            }
        }
        Some("time") => {
            let repo = &args[2];
            let rev = args.get(3).map_or("HEAD", String::as_str);
            let start = Instant::now();
            let rows = scan(repo, rev, None);
            let elapsed = start.elapsed();
            writeln!(out, "files\t{}\tms\t{}", rows.len(), elapsed.as_millis()).unwrap();
        }
        _ => {
            eprintln!("usage: sizes scan REPO [REV] | change REPO BASE HEAD | time REPO [REV]");
            std::process::exit(2);
        }
    }
}
