// @generated by payments-codegen. DO NOT EDIT.
use crate::http::client::post_json;

pub struct KlarnaProvider;

impl KlarnaProvider {
    pub fn charge(&self, cents: u64) -> crate::Result<String> {
        post_json("/klarna/orders", &format!("{{\"amount\":{cents}}}"))
    }

    pub fn refund(&self, charge_id: &str) -> crate::Result<()> {
        post_json(&format!("/klarna/orders/{charge_id}/refund"), "{}").map(|_| ())
    }
}
