#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

here=$(cd "$(dirname "$0")" && pwd)
query='language:Python stars:1000..20000 pushed:>=2026-09-15 archived:false mirror:false size:<=150000'
[ -f "$here/search-python-100.json" ] ||
  gh api -X GET search/repositories -f q="$query" -f sort=stars -f order=desc -f per_page=100 -f page=1 > "$here/search-python-100.json"

lock='(^|/)(uv\.lock|poetry\.lock|pdm\.lock|Pipfile\.lock|pylock(\.[^/]+)?\.toml)$'
: > "$here/survey-python.tsv"
while read -r name branch; do
  tree=$(gh api "repos/$name/git/trees/$branch?recursive=1" < /dev/null 2> /dev/null || echo '{}')
  truncated=$(jq -r 'if has("truncated") then .truncated else "error" end' <<< "$tree")
  paths=$(jq -r '.tree[]? | select(.type == "blob") | .path' <<< "$tree")
  root=$(grep -cxE 'pyproject\.toml|setup\.py|setup\.cfg' <<< "$paths" || true)
  [ "$root" -gt 0 ] || { printf '%s\t%s\tno-root-project\n' "$name" "$truncated" >> "$here/survey-python.tsv"; continue; }
  formats=$({ grep -E "$lock" <<< "$paths" || true; } | sed -E 's|.*/||; s|^pylock\..*\.toml$|pylock.toml|' | sort | uniq -c | awk '{ printf "%s%s:%s", sep, $2, $1; sep="," }')
  rootlock=$(grep -E '^(uv\.lock|poetry\.lock|pdm\.lock|Pipfile\.lock|pylock(\.[^/]+)?\.toml)$' <<< "$paths" | paste -sd, - || true)
  reqs=$(grep -E '(^|/)requirements[^/]*\.txt$|(^|/)requirements/[^/]*\.txt$' <<< "$paths" | head -40 || true)
  hashed=0
  compiled=0
  for req in $reqs; do
    body=$(gh api < /dev/null -H 'Accept: application/vnd.github.raw' "repos/$name/contents/$req?ref=$branch" 2> /dev/null | head -c 20000 || true)
    grep -q -- '--hash=' <<< "$body" && hashed=$((hashed + 1))
    grep -qE 'autogenerated by (pip-compile|uv)' <<< "$body" && compiled=$((compiled + 1))
  done
  printf '%s\t%s\troot-project\troot-lock=%s\tlocks=%s\trequirements=%s\thashed=%s\tcompiled=%s\n' \
    "$name" "$truncated" "${rootlock:--}" "${formats:--}" "$(wc -w <<< "$reqs" | tr -d ' ')" "$hashed" "$compiled" >> "$here/survey-python.tsv"
done < <(jq -r '.items[] | "\(.full_name) \(.default_branch)"' "$here/search-python-100.json")
wc -l "$here/survey-python.tsv"
