use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use tree_sitter::{Node, Parser};

#[derive(Clone, Copy, PartialEq)]
enum Lang {
    Rust,
    Python,
    Ts,
}

struct Site {
    candidate: &'static str,
    shape: String,
    file: String,
    line: usize,
    exclusions: Vec<&'static str>,
    text: String,
    name: Option<String>,
}

struct File<'a> {
    lang: Lang,
    path: &'a str,
    src: &'a [u8],
    lines: Vec<&'a str>,
    test: bool,
    generated: bool,
    example: bool,
    stub_file: bool,
    test_ranges: Vec<(usize, usize)>,
}

const SKIP_DIRS: &[&str] = &[
    ".git", "node_modules", "vendor", "build", ".build", "dist", "target", "__pycache__", ".venv",
    "venv", "coverage", ".next", "out", "fixtures",
];

const TEST_SEGMENTS: &[&str] = &[
    "test", "tests", "__tests__", "spec", "specs", "testing", "e2e", "__mocks__", "mocks",
    "testdata", "test_utils", "testutils",
];

const EXAMPLE_SEGMENTS: &[&str] = &["examples", "example", "benches", "bench", "docs", "demo", "demos"];

const MOCK_WORDS: &[&str] = &[
    "mock", "mocks", "mocked", "fake", "fakes", "faked", "dummy", "dummies", "placeholder",
    "placeholders",
];

const LEXICON: &[&str] = &[
    "in a real implementation",
    "in a real app",
    "in a real application",
    "in a real system",
    "in a real scenario",
    "in a real world",
    "in production, you",
    "in production you",
    "real implementation",
    "actual implementation",
    "replace with actual",
    "replace with real",
    "replace this with",
    "should be replaced",
    "needs to be implemented",
    "to be implemented",
    "not yet implemented",
    "not implemented yet",
    "not supported yet",
    "not yet supported",
    "coming soon",
    "later release",
    "future release",
    "future version",
    "simplified version",
    "simplified implementation",
    "simplified logic",
    "temporary implementation",
    "temporary fix",
    "hardcoded for now",
    "hard-coded for now",
    "mock data",
    "mock implementation",
    "mock response",
    "dummy data",
    "dummy implementation",
    "fake data",
    "for demonstration",
    "for demo purposes",
    "for simplicity",
    "would normally",
    "for now",
    "placeholder",
    "stub",
];

const LOG_TAILS: &[&str] = &[
    "log", "warn", "warning", "error", "info", "debug", "trace", "exception", "critical",
];

const RUST_LOG_MACROS: &[&str] = &[
    "println", "eprintln", "print", "eprint", "dbg", "log", "trace", "debug", "info", "warn", "error",
];

fn lang_of(path: &str) -> Option<(Lang, tree_sitter::Language)> {
    let ext = path.rsplit('.').next()?;
    Some(match ext {
        "rs" => (Lang::Rust, tree_sitter_rust::LANGUAGE.into()),
        "py" | "pyi" => (Lang::Python, tree_sitter_python::LANGUAGE.into()),
        "ts" | "mts" | "cts" => (Lang::Ts, tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into()),
        "tsx" => (Lang::Ts, tree_sitter_typescript::LANGUAGE_TSX.into()),
        _ => return None,
    })
}

fn text<'a>(node: Node, src: &'a [u8]) -> &'a str {
    node.utf8_text(src).unwrap_or_default()
}

fn named_children(node: Node) -> Vec<Node> {
    let mut cursor = node.walk();
    node.named_children(&mut cursor).collect()
}

fn is_comment(node: Node) -> bool {
    node.kind().contains("comment")
}

fn path_is_test(path: &str) -> bool {
    let segments: Vec<&str> = path.split('/').collect();
    let (dirs, name) = segments.split_at(segments.len() - 1);
    let name = name[0];
    dirs.iter().any(|dir| TEST_SEGMENTS.contains(dir))
        || name.starts_with("test_")
        || name.ends_with("_test.py")
        || name.ends_with("_test.rs")
        || name == "conftest.py"
        || name == "tests.rs"
        || name.contains(".test.")
        || name.contains(".spec.")
        || name.contains(".stories.")
}

fn path_is_example(path: &str) -> bool {
    path.split('/').rev().skip(1).any(|dir| EXAMPLE_SEGMENTS.contains(&dir))
}

fn is_generated(src: &[u8]) -> bool {
    let head = String::from_utf8_lossy(&src[..src.len().min(2048)]).to_lowercase();
    ["@generated", "do not edit", "auto-generated", "autogenerated", "code generated"]
        .iter()
        .any(|marker| head.contains(marker))
}

fn cfg_test_ranges(root: Node, src: &[u8], out: &mut Vec<(usize, usize)>) {
    let children = named_children(root);
    for (index, child) in children.iter().enumerate() {
        if child.kind() == "attribute_item" && text(*child, src).replace(' ', "").contains("cfg(test)") {
            if let Some(item) = children[index + 1..].iter().find(|next| next.kind() != "attribute_item" && !is_comment(**next)) {
                out.push((item.start_position().row, item.end_position().row));
            }
        }
        if child.kind() == "mod_item" {
            if let Some(body) = child.child_by_field_name("body") {
                cfg_test_ranges(body, src, out);
            }
        }
    }
}

impl<'a> File<'a> {
    fn new(lang: Lang, path: &'a str, src: &'a [u8]) -> Self {
        File {
            lang,
            path,
            src,
            lines: std::str::from_utf8(src).unwrap_or_default().lines().collect(),
            test: path_is_test(path),
            generated: is_generated(src),
            example: path_is_example(path),
            stub_file: path.ends_with(".pyi") || path.ends_with(".d.ts"),
            test_ranges: Vec::new(),
        }
    }

    fn site(&self, candidate: &'static str, shape: &str, row: usize, mut exclusions: Vec<&'static str>) -> Site {
        if self.test || self.test_ranges.iter().any(|(from, to)| (*from..=*to).contains(&row)) {
            exclusions.push("test");
        }
        if self.generated {
            exclusions.push("generated");
        }
        if self.example {
            exclusions.push("example");
        }
        exclusions.sort();
        exclusions.dedup();
        Site {
            candidate,
            shape: shape.to_string(),
            file: self.path.to_string(),
            line: row + 1,
            exclusions,
            text: self.lines.get(row).map(|line| line.trim()).unwrap_or_default().to_string(),
            name: None,
        }
    }
}

fn strip(node: Node) -> Node {
    match node.kind() {
        "parenthesized_expression" | "as_expression" | "satisfies_expression" | "type_assertion" | "non_null_expression" => {
            named_children(node).into_iter().find(|child| !child.kind().contains("type")).map(strip).unwrap_or(node)
        }
        _ => node,
    }
}

fn empty_args(node: Node) -> bool {
    node.child_by_field_name("arguments").is_none_or(|args| named_children(args).iter().all(|child| is_comment(*child)))
}

fn constant(node: Node, file: &File) -> Option<&'static str> {
    let node = strip(node);
    let src = file.src;
    let body = text(node, src);
    let none_named = named_children(node).iter().all(|child| is_comment(*child));
    match file.lang {
        Lang::Ts => match node.kind() {
            "array" | "object" if none_named => Some("empty"),
            "null" | "undefined" => Some("empty"),
            "number" if body == "0" => Some("empty"),
            "string" | "template_string" if none_named => Some("empty"),
            "new_expression" => {
                let constructor = node.child_by_field_name("constructor").map(|c| text(c, src));
                (matches!(constructor, Some("Map" | "Set" | "Array" | "Object")) && empty_args(node)).then_some("empty")
            }
            "call_expression" => {
                let callee = node.child_by_field_name("function").map(|c| text(c, src)).unwrap_or_default();
                let args: Vec<Node> = node.child_by_field_name("arguments").map(named_children).unwrap_or_default();
                match (callee, args.as_slice()) {
                    ("Promise.resolve", []) => Some("wrapped"),
                    ("Promise.resolve", [only]) if constant(*only, file).is_some() => Some("wrapped"),
                    _ => None,
                }
            }
            _ => None,
        },
        Lang::Python => match node.kind() {
            "list" | "dictionary" | "tuple" | "set" if none_named => Some("empty"),
            "none" => Some("empty"),
            "integer" if body == "0" => Some("empty"),
            "string" if !named_children(node).iter().any(|child| child.kind() == "string_content" || child.kind() == "interpolation") => Some("empty"),
            "call" => {
                let callee = node.child_by_field_name("function").map(|c| text(c, src)).unwrap_or_default();
                (matches!(callee, "list" | "dict" | "set" | "tuple" | "str" | "frozenset") && empty_args(node)).then_some("empty")
            }
            _ => None,
        },
        Lang::Rust => match node.kind() {
            "unit_expression" => Some("empty"),
            "array_expression" if none_named => Some("empty"),
            "string_literal" if none_named => Some("empty"),
            "integer_literal" if body == "0" => Some("empty"),
            "identifier" if body == "None" => Some("empty"),
            "macro_invocation" => {
                let name = node.child_by_field_name("macro").map(|m| text(m, src)).unwrap_or_default();
                let tokens = named_children(node).into_iter().find(|child| child.kind() == "token_tree").map(|t| text(t, src).replace(char::is_whitespace, ""));
                (name == "vec" && matches!(tokens.as_deref(), Some("[]" | "()"))).then_some("empty")
            }
            "call_expression" => {
                let callee = node.child_by_field_name("function").unwrap_or(node);
                let args: Vec<Node> = node.child_by_field_name("arguments").map(named_children).unwrap_or_default();
                let callee_text = text(callee, src);
                if callee.kind() == "scoped_identifier" && args.is_empty() {
                    let name = callee.child_by_field_name("name").map(|n| text(n, src)).unwrap_or_default();
                    let path = callee.child_by_field_name("path").map(|p| text(p, src)).unwrap_or_default();
                    let collection = matches!(
                        path.rsplit("::").next().unwrap_or(path),
                        "Vec" | "String" | "HashMap" | "HashSet" | "BTreeMap" | "BTreeSet" | "VecDeque" | "IndexMap" | "IndexSet"
                    );
                    return (name == "default" || (name == "new" && collection)).then_some("empty");
                }
                match (callee_text, args.as_slice()) {
                    ("Ok" | "Some", [only]) if constant(*only, file).is_some() => Some("wrapped"),
                    _ => None,
                }
            }
            _ => None,
        },
    }
}

fn statements(block: Node) -> (Vec<Node>, bool) {
    let children = named_children(block);
    let commented = children.iter().any(|child| is_comment(*child));
    (children.into_iter().filter(|child| !is_comment(*child)).collect(), commented)
}

fn without_docstring<'t>(statements: &'t [Node<'t>], lang: Lang) -> (&'t [Node<'t>], bool) {
    if lang == Lang::Python {
        if let Some(first) = statements.first() {
            if first.kind() == "expression_statement" && named_children(*first).first().is_some_and(|child| child.kind() == "string") {
                return (&statements[1..], true);
            }
        }
    }
    (statements, false)
}

fn returned<'t>(statement: Node<'t>, lang: Lang, tail: bool) -> Option<Option<Node<'t>>> {
    match (lang, statement.kind()) {
        (Lang::Rust, "expression_statement") => {
            let inner = statement.named_child(0)?;
            (inner.kind() == "return_expression").then(|| inner.named_child(0))
        }
        (Lang::Rust, _) if tail => Some(Some(statement)),
        (_, "return_statement") => Some(statement.named_child(0)),
        _ => None,
    }
}

fn function_name(node: Node, src: &[u8]) -> Option<String> {
    if let Some(name) = node.child_by_field_name("name") {
        return Some(text(name, src).to_string());
    }
    let parent = node.parent()?;
    match parent.kind() {
        "variable_declarator" | "public_field_definition" | "pair" | "assignment_expression" => parent
            .child_by_field_name("name")
            .or_else(|| parent.child_by_field_name("left"))
            .or_else(|| parent.child_by_field_name("key"))
            .map(|name| text(name, src).to_string()),
        _ => None,
    }
}

fn decorated_with(node: Node, src: &[u8], wanted: &[&str]) -> bool {
    named_children(node)
        .into_iter()
        .filter(|child| child.kind() == "decorator")
        .any(|decorator| {
            let body = text(decorator, src).trim_start_matches('@');
            let callee = body.split('(').next().unwrap_or(body);
            wanted.contains(&callee.rsplit('.').next().unwrap_or(callee))
        })
}

fn function_exclusions(node: Node, file: &File) -> Vec<&'static str> {
    let src = file.src;
    let mut out = Vec::new();
    if file.stub_file {
        out.push("declared");
    }
    if let Some(previous) = node.prev_named_sibling() {
        if is_comment(previous) && previous.end_position().row + 1 >= node.start_position().row {
            out.push("documented");
        }
    }
    let mut above = node.parent();
    while let Some(holder) = above {
        match holder.kind() {
            "decorated_definition" => {
                if decorated_with(holder, src, &["abstractmethod", "abstractproperty", "overload"]) {
                    out.push("declared");
                }
                if let Some(previous) = holder.prev_named_sibling() {
                    if is_comment(previous) && previous.end_position().row + 1 >= holder.start_position().row {
                        out.push("documented");
                    }
                }
            }
            "class_definition" => {
                if let Some(bases) = holder.child_by_field_name("superclasses") {
                    let names: Vec<&str> = named_children(bases).into_iter().map(|base| text(base, src)).collect();
                    if names.iter().any(|name| matches!(name.rsplit('.').next().unwrap_or(name), "Protocol" | "ABC" | "ABCMeta") || name.contains("metaclass=ABCMeta")) {
                        out.push("declared");
                    } else if names.iter().any(|name| *name != "object") {
                        out.push("override");
                    }
                }
                break;
            }
            "class_declaration" | "class" => {
                if named_children(holder).iter().any(|child| child.kind() == "class_heritage") {
                    out.push("override");
                }
                break;
            }
            "abstract_class_declaration" => {
                out.push("base-default");
                break;
            }
            "trait_item" => {
                out.push("trait-default");
                break;
            }
            "impl_item" => {
                if holder.child_by_field_name("trait").is_some() {
                    out.push("trait-impl");
                }
                break;
            }
            "function_item" | "function_definition" | "function_declaration" | "method_definition" => break,
            _ => {}
        }
        above = holder.parent();
    }
    out
}

fn function_body(node: Node, file: &File, out: &mut Vec<Site>) {
    let Some(body) = node.child_by_field_name("body") else { return };
    let name = function_name(node, file.src);
    let row = node.start_position().row;
    if !matches!(body.kind(), "block" | "statement_block") {
        if node.kind() == "arrow_function" && constant(body, file).is_some() {
            let declared_at_top = node.parent().is_some_and(|parent| match parent.kind() {
                "variable_declarator" => parent.parent().and_then(|p| p.parent()).is_some_and(|p| matches!(p.kind(), "program" | "export_statement")),
                "public_field_definition" => true,
                _ => false,
            });
            if declared_at_top {
                let mut exclusions = function_exclusions(node, file);
                exclusions.push("arrow");
                let mut site = file.site("constant-return", &format!("arrow-{}", constant(body, file).unwrap()), row, exclusions);
                site.name = name;
                out.push(site);
            }
        }
        return;
    }
    let (all, commented) = statements(body);
    let (rest, docstring) = without_docstring(&all, file.lang);
    let mut exclusions = function_exclusions(node, file);
    if commented {
        exclusions.push("commented");
    }
    if docstring {
        exclusions.push("documented");
    }
    match rest {
        [only] if file.lang == Lang::Python && only.kind() == "expression_statement" && only.named_child(0).is_some_and(|child| child.kind() == "ellipsis") => {
            out.push(file.site("ellipsis-body", "ellipsis", row, exclusions));
        }
        [only] => {
            if let Some(shape) = throws(*only, file) {
                if already_a_stub(*only, file) {
                    exclusions.push("stubs");
                }
                let mut site = file.site("throw-body", shape, row, exclusions);
                site.name = name;
                out.push(site);
            } else if let Some(Some(value)) = returned(*only, file.lang, true) {
                if let Some(kind) = constant(value, file) {
                    let mut site = file.site("constant-return", &format!("return-{kind}"), row, exclusions);
                    site.name = name;
                    out.push(site);
                }
            }
        }
        _ => {}
    }
}

fn throws(statement: Node, file: &File) -> Option<&'static str> {
    let src = file.src;
    match (file.lang, statement.kind()) {
        (Lang::Python, "raise_statement") => Some("raise"),
        (Lang::Ts, "throw_statement") => Some("throw"),
        (Lang::Rust, _) => {
            let inner = if statement.kind() == "expression_statement" { statement.named_child(0)? } else { statement };
            let inner = if inner.kind() == "return_expression" { inner.named_child(0)? } else { inner };
            match inner.kind() {
                "macro_invocation" => {
                    let name = inner.child_by_field_name("macro").map(|m| text(m, src)).unwrap_or_default();
                    matches!(name, "panic" | "unreachable" | "todo" | "unimplemented" | "bail").then_some("panic")
                }
                "call_expression" => inner.child_by_field_name("function").is_some_and(|f| text(f, src) == "Err").then_some("err-return"),
                _ => None,
            }
        }
        _ => None,
    }
}

fn already_a_stub(statement: Node, file: &File) -> bool {
    let body = text(statement, file.src);
    match file.lang {
        Lang::Rust => body.contains("todo!(") || body.contains("unimplemented!("),
        Lang::Python => body.contains("raise NotImplementedError"),
        Lang::Ts => body.contains("throw new") && body.contains("Error(") && body.to_lowercase().contains("not implemented"),
    }
}

fn is_log_call(node: Node, file: &File) -> bool {
    let src = file.src;
    let node = if node.kind() == "expression_statement" { match node.named_child(0) { Some(inner) => inner, None => return false } } else { node };
    let node = if node.kind() == "await_expression" { node.named_child(0).unwrap_or(node) } else { node };
    match file.lang {
        Lang::Rust => {
            if node.kind() != "macro_invocation" {
                return false;
            }
            let name = node.child_by_field_name("macro").map(|m| text(m, src)).unwrap_or_default();
            RUST_LOG_MACROS.contains(&name.rsplit("::").next().unwrap_or(name))
        }
        Lang::Python | Lang::Ts => {
            if !matches!(node.kind(), "call" | "call_expression") {
                return false;
            }
            let callee = node.child_by_field_name("function").map(|f| text(f, src)).unwrap_or_default();
            if matches!(callee, "print" | "traceback.print_exc" | "warnings.warn") {
                return true;
            }
            let Some((object, tail)) = callee.rsplit_once('.') else { return false };
            LOG_TAILS.contains(&tail) && (object.to_lowercase().contains("log") || object == "console")
        }
    }
}

fn mentions(node: Node, src: &[u8], kinds: &[&str], texts: &[&str]) -> bool {
    if kinds.contains(&node.kind()) {
        return true;
    }
    if node.kind() == "macro_invocation" {
        let name = node.child_by_field_name("macro").map(|m| text(m, src)).unwrap_or_default();
        if matches!(name, "panic" | "bail" | "unreachable" | "todo" | "unimplemented") {
            return true;
        }
    }
    if node.kind() == "call_expression" || node.kind() == "identifier" {
        let body = text(node, src);
        if texts.iter().any(|wanted| body.starts_with(wanted)) {
            return true;
        }
    }
    named_children(node).into_iter().any(|child| mentions(child, src, kinds, texts))
}

fn propagates(node: Node, file: &File) -> bool {
    match file.lang {
        Lang::Rust => mentions(node, file.src, &["try_expression"], &["Err(", "Err"]),
        Lang::Python => mentions(node, file.src, &["raise_statement"], &[]),
        Lang::Ts => mentions(node, file.src, &["throw_statement"], &["Promise.reject"]),
    }
}

fn handler(statements: &[Node], commented: bool, file: &File, row: usize, exclusions: Vec<&'static str>, broad: bool, shape_prefix: &str, whole: Node, out: &mut Vec<Site>) {
    let mut exclusions = exclusions;
    if commented {
        exclusions.push("commented");
    }
    if !broad {
        exclusions.push("specific");
    }
    let terminal = |node: &Node| -> Option<&'static str> {
        match node.kind() {
            "pass_statement" => Some("pass"),
            "continue_statement" | "continue_expression" => Some("continue"),
            "break_statement" => Some("break"),
            "expression_statement" if file.lang == Lang::Python && node.named_child(0).is_some_and(|c| c.kind() == "ellipsis") => Some("pass"),
            "expression_statement" if file.lang == Lang::Rust && node.named_child(0).is_some_and(|c| matches!(c.kind(), "continue_expression" | "break_expression")) => Some("continue"),
            _ => match returned(*node, file.lang, true) {
                Some(None) => Some("return"),
                Some(Some(value)) if constant(value, file).is_some() => Some("default"),
                _ => None,
            },
        }
    };
    let typed_return = |file: &File| -> bool {
        let mut above = whole.parent();
        while let Some(holder) = above {
            if matches!(holder.kind(), "function_item" | "function_definition" | "function_declaration" | "method_definition" | "arrow_function" | "function_expression") {
                let returns = holder.child_by_field_name("return_type").map(|r| text(r, file.src)).unwrap_or_default();
                return ["Option", "None", "null", "undefined", "Optional", "Result"].iter().any(|word| returns.contains(word));
            }
            above = holder.parent();
        }
        false
    };
    let shape = |name: &str| format!("{shape_prefix}{name}");
    match statements {
        [] => out.push(file.site("empty-handler", &shape("empty"), row, exclusions)),
        [only] => match terminal(only) {
            Some("default") => {
                if typed_return(file) {
                    exclusions.push("typed-return");
                }
                out.push(file.site("default-handler", &shape("return-constant"), row, exclusions));
            }
            Some(kind) => out.push(file.site("empty-handler", &shape(kind), row, exclusions)),
            None if is_log_call(*only, file) => out.push(file.site("log-handler", &shape("log"), row, exclusions)),
            None if broad && !propagates(*only, file) => out.push(file.site("broad-handler", &shape("other"), row, exclusions)),
            None => {}
        },
        [logs @ .., last] if logs.iter().all(|node| is_log_call(*node, file)) && (is_log_call(*last, file) || terminal(last).is_some()) => {
            out.push(file.site("log-handler", &shape(if is_log_call(*last, file) { "log" } else { "log-default" }), row, exclusions));
        }
        _ if broad && !statements.iter().any(|node| propagates(*node, file)) => {
            out.push(file.site("broad-handler", &shape("other"), row, exclusions));
        }
        _ => {}
    }
}

fn python_broad(clause: Node, src: &[u8]) -> bool {
    let types: Vec<Node> = named_children(clause).into_iter().filter(|child| child.kind() != "block" && !is_comment(*child)).collect();
    let Some(first) = types.first() else { return true };
    let first = if first.kind() == "as_pattern" { first.named_child(0).unwrap_or(*first) } else { *first };
    let names: Vec<&str> = if first.kind() == "tuple" { named_children(first).into_iter().map(|n| text(n, src)).collect() } else { vec![text(first, src)] };
    names.iter().any(|name| matches!(name.rsplit('.').next().unwrap_or(name), "Exception" | "BaseException"))
}

fn handlers(node: Node, file: &File, out: &mut Vec<Site>) {
    let src = file.src;
    let row = node.start_position().row;
    match (file.lang, node.kind()) {
        (Lang::Ts, "catch_clause") => {
            if let Some(body) = node.child_by_field_name("body") {
                let (statements, commented) = statements(body);
                let narrows = text(body, src).contains("instanceof");
                handler(&statements, commented, file, row, Vec::new(), !narrows, "", node, out);
            }
        }
        (Lang::Ts, "call_expression") => {
            let callee = node.child_by_field_name("function");
            let is_catch = callee.is_some_and(|f| f.kind() == "member_expression" && f.child_by_field_name("property").is_some_and(|p| text(p, src) == "catch"));
            if !is_catch {
                return;
            }
            let Some(callback) = node.child_by_field_name("arguments").and_then(|args| named_children(args).into_iter().next()) else { return };
            if !matches!(callback.kind(), "arrow_function" | "function_expression") {
                return;
            }
            let Some(body) = callback.child_by_field_name("body") else { return };
            if body.kind() == "statement_block" {
                let (statements, commented) = statements(body);
                let narrows = text(body, src).contains("instanceof");
                handler(&statements, commented, file, row, Vec::new(), !narrows, "promise-", node, out);
            } else if constant(body, file).is_some() {
                out.push(file.site("default-handler", "promise-return-constant", row, Vec::new()));
            } else if is_log_call(body, file) {
                out.push(file.site("log-handler", "promise-log", row, Vec::new()));
            }
        }
        (Lang::Python, "except_clause") => {
            if let Some(block) = named_children(node).into_iter().find(|child| child.kind() == "block") {
                let (statements, commented) = statements(block);
                let bare = !named_children(node).iter().any(|child| child.kind() != "block" && !is_comment(*child));
                let exclusions = if bare { vec!["escapes"] } else { Vec::new() };
                handler(&statements, commented, file, row, exclusions, python_broad(node, src), "", node, out);
            }
        }
        (Lang::Python, "with_statement") => {
            for item in named_children(node).into_iter().filter(|c| c.kind() == "with_clause").flat_map(named_children) {
                let Some(call) = item.child_by_field_name("value") else { continue };
                if call.kind() != "call" {
                    continue;
                }
                let callee = call.child_by_field_name("function").map(|f| text(f, src)).unwrap_or_default();
                if callee.rsplit('.').next() == Some("suppress") {
                    let args = call.child_by_field_name("arguments").map(|a| text(a, src)).unwrap_or_default();
                    let broad = args.contains("Exception") && !args.contains("Error");
                    let exclusions = if broad { Vec::new() } else { vec!["specific"] };
                    out.push(file.site("empty-handler", "suppress", row, exclusions));
                }
            }
        }
        (Lang::Rust, "match_arm") => {
            let Some(pattern) = node.child_by_field_name("pattern") else { return };
            let Some(inner) = named_children(pattern).into_iter().find(|c| c.kind() == "tuple_struct_pattern") else { return };
            if inner.child_by_field_name("type").map(|t| text(t, src)) != Some("Err") {
                return;
            }
            let bound: Vec<Node> = named_children(inner).into_iter().skip(1).collect();
            let guarded = pattern.child_by_field_name("condition").is_some();
            let broad = !guarded && (bound.is_empty() || bound.iter().all(|b| b.kind() == "identifier" || text(*b, src) == ".."));
            let Some(value) = node.child_by_field_name("value") else { return };
            if value.kind() == "block" {
                let (statements, commented) = statements(value);
                handler(&statements, commented, file, row, Vec::new(), broad, "err-arm-", node, out);
            } else {
                handler(&[value], false, file, row, Vec::new(), broad, "err-arm-", node, out);
            }
        }
        (Lang::Rust, "let_declaration") => {
            let wildcard = node.child_by_field_name("pattern").is_some_and(|p| text(p, src) == "_");
            let value = node.child_by_field_name("value");
            if wildcard && value.is_some_and(|v| matches!(v.kind(), "call_expression" | "await_expression" | "try_expression" | "macro_invocation")) {
                out.push(file.site("empty-handler", "let-underscore", row, Vec::new()));
            }
        }
        (Lang::Rust, "call_expression") => {
            let Some(callee) = node.child_by_field_name("function") else { return };
            if callee.kind() != "field_expression" {
                return;
            }
            let method = callee.child_by_field_name("field").map(|f| text(f, src)).unwrap_or_default();
            let args: Vec<Node> = node.child_by_field_name("arguments").map(named_children).unwrap_or_default();
            match (method, args.as_slice()) {
                ("ok", []) if node.parent().is_some_and(|p| p.kind() == "expression_statement") => {
                    out.push(file.site("empty-handler", "ok-discard", row, Vec::new()));
                }
                ("unwrap_or_default", []) => out.push(file.site("default-handler", "unwrap-or-default", row, Vec::new())),
                ("unwrap_or", [only]) if constant(*only, file).is_some() => out.push(file.site("default-handler", "unwrap-or", row, Vec::new())),
                ("unwrap_or_else", [only]) if only.kind() == "closure_expression" && only.child_by_field_name("body").is_some_and(|b| constant(b, file).is_some()) => {
                    out.push(file.site("default-handler", "unwrap-or-else", row, Vec::new()));
                }
                _ => {}
            }
        }
        _ => {}
    }
}

fn wording(node: Node, file: &File, out: &mut Vec<Site>) {
    let literal = match file.lang {
        Lang::Rust => matches!(node.kind(), "string_literal" | "raw_string_literal"),
        Lang::Python => node.kind() == "string",
        Lang::Ts => matches!(node.kind(), "string" | "template_string"),
    };
    if !literal && (!is_comment(node) || node.parent().is_some_and(is_comment)) {
        return;
    }
    let body = text(node, file.src).to_lowercase();
    let base = node.start_position().row;
    let mut seen: HashSet<usize> = HashSet::new();
    for phrase in LEXICON {
        let mut from = 0;
        while let Some(at) = body[from..].find(phrase) {
            let start = from + at;
            let end = start + phrase.len();
            from = end;
            let before = body[..start].chars().next_back();
            let after = body[end..].chars().next();
            if before.is_some_and(|c| c.is_alphanumeric()) || after.is_some_and(|c| c.is_alphanumeric() && !(*phrase == "stub" && c == 's')) {
                continue;
            }
            let row = base + body[..start].matches('\n').count();
            if seen.insert(row) {
                let kind = if literal { "literal" } else { "comment" };
                out.push(file.site("placeholder-wording", &format!("{kind}:{phrase}"), row, Vec::new()));
            }
        }
    }
}

fn words(name: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (index, c) in chars.iter().enumerate() {
        let boundary = !c.is_alphanumeric()
            || (c.is_uppercase() && index > 0 && (chars[index - 1].is_lowercase() || chars.get(index + 1).is_some_and(|n| n.is_lowercase())));
        if boundary && !current.is_empty() {
            out.push(current.to_lowercase());
            current.clear();
        }
        if c.is_alphanumeric() {
            current.push(*c);
        }
    }
    if !current.is_empty() {
        out.push(current.to_lowercase());
    }
    out
}

fn mock_names(node: Node, file: &File, out: &mut Vec<Site>) {
    let src = file.src;
    let declared = match (file.lang, node.kind()) {
        (Lang::Rust, "function_item" | "const_item" | "static_item" | "struct_item" | "enum_item") => node.child_by_field_name("name"),
        (Lang::Rust, "let_declaration") => node.child_by_field_name("pattern").filter(|p| p.kind() == "identifier"),
        (Lang::Python, "function_definition" | "class_definition") => node.child_by_field_name("name"),
        (Lang::Python, "assignment") => node.child_by_field_name("left").filter(|l| l.kind() == "identifier"),
        (Lang::Ts, "function_declaration" | "class_declaration" | "method_definition" | "variable_declarator" | "public_field_definition") => {
            node.child_by_field_name("name").filter(|n| matches!(n.kind(), "identifier" | "property_identifier" | "type_identifier"))
        }
        _ => None,
    };
    if let Some(name) = declared {
        if words(text(name, src)).iter().any(|word| MOCK_WORDS.contains(&word.as_str())) {
            out.push(file.site("mock-name", "declaration", name.start_position().row, Vec::new()));
        }
        return;
    }
    let literal = match file.lang {
        Lang::Rust => node.kind() == "string_literal",
        Lang::Python => node.kind() == "string",
        Lang::Ts => matches!(node.kind(), "string" | "template_string"),
    };
    if literal && words(text(node, src)).iter().any(|word| MOCK_WORDS.contains(&word.as_str())) {
        out.push(file.site("mock-name", "literal", node.start_position().row, Vec::new()));
    }
}

fn is_function(node: Node, lang: Lang) -> bool {
    match lang {
        Lang::Rust => node.kind() == "function_item",
        Lang::Python => node.kind() == "function_definition",
        Lang::Ts => matches!(node.kind(), "function_declaration" | "method_definition" | "arrow_function" | "function_expression" | "generator_function_declaration" | "function"),
    }
}

fn visit(node: Node, file: &File, out: &mut Vec<Site>) {
    if is_function(node, file.lang) {
        function_body(node, file, out);
    }
    handlers(node, file, out);
    wording(node, file, out);
    mock_names(node, file, out);
    let mut cursor = node.walk();
    for child in node.children(&mut cursor) {
        visit(child, file, out);
    }
}

struct Timing {
    parse: Duration,
    walk: Duration,
}

fn sites_of(path: &str, src: &[u8], timing: &mut Timing) -> Vec<Site> {
    let Some((lang, grammar)) = lang_of(path) else { return Vec::new() };
    let started = Instant::now();
    let mut parser = Parser::new();
    parser.set_language(&grammar).expect("grammar");
    let Some(tree) = parser.parse(src, None) else { return Vec::new() };
    timing.parse += started.elapsed();
    let started = Instant::now();
    let mut file = File::new(lang, path, src);
    if lang == Lang::Rust {
        cfg_test_ranges(tree.root_node(), src, &mut file.test_ranges);
    }
    let mut out = Vec::new();
    visit(tree.root_node(), &file, &mut out);
    timing.walk += started.elapsed();
    out
}

fn walk_tree(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    let mut entries: Vec<PathBuf> = entries.filter_map(|e| e.ok()).map(|e| e.path()).collect();
    entries.sort();
    for path in entries {
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default();
        if path.is_symlink() {
            continue;
        }
        if path.is_dir() {
            if !SKIP_DIRS.contains(&name) {
                walk_tree(root, &path, out);
            }
        } else if lang_of(name).is_some() {
            out.push(path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/"));
        }
    }
}

fn reference_counts(root: &Path, files: &[String]) -> HashMap<String, usize> {
    let mut counts = HashMap::new();
    for file in files {
        if path_is_test(file) {
            continue;
        }
        let Ok(src) = std::fs::read(root.join(file)) else { continue };
        for word in String::from_utf8_lossy(&src).split(|c: char| !(c.is_alphanumeric() || c == '_')) {
            if !word.is_empty() {
                *counts.entry(word.to_string()).or_insert(0) += 1;
            }
        }
    }
    counts
}

fn analyze(root: &Path, only: Option<&HashSet<String>>, timing: &mut Timing) -> Vec<Site> {
    let mut files = Vec::new();
    walk_tree(root, root, &mut files);
    let counts = reference_counts(root, &files);
    let mut out = Vec::new();
    for file in &files {
        if only.is_some_and(|set| !set.contains(file)) {
            continue;
        }
        let Ok(src) = std::fs::read(root.join(file)) else { continue };
        for mut site in sites_of(file, &src, timing) {
            if let Some(name) = &site.name {
                if counts.get(name).copied().unwrap_or(0) < 2 {
                    site.exclusions.push("unreferenced");
                    site.exclusions.sort();
                }
            }
            out.push(site);
        }
    }
    out
}

fn print(sites: &[&Site]) {
    for site in sites {
        let exclusions = if site.exclusions.is_empty() { "-".to_string() } else { site.exclusions.join(",") };
        println!("{}\t{}\t{}\t{}\t{}\t{}", site.candidate, site.shape, site.file, site.line, exclusions, site.text);
    }
}

fn key(site: &Site) -> (&'static str, String, String) {
    (site.candidate, site.file.clone(), site.text.clone())
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut timing = Timing { parse: Duration::ZERO, walk: Duration::ZERO };
    match args.first().map(String::as_str) {
        Some("scan") => {
            let only: Option<HashSet<String>> = (args.len() > 2).then(|| args[2..].iter().cloned().collect());
            let sites = analyze(Path::new(&args[1]), only.as_ref(), &mut timing);
            print(&sites.iter().collect::<Vec<_>>());
        }
        Some("new") => {
            let only: Option<HashSet<String>> = (args.len() > 3).then(|| args[3..].iter().cloned().collect());
            let before = analyze(Path::new(&args[1]), only.as_ref(), &mut timing);
            let after = analyze(Path::new(&args[2]), only.as_ref(), &mut timing);
            let mut held: BTreeMap<(&'static str, String, String), usize> = BTreeMap::new();
            for site in &before {
                *held.entry(key(site)).or_insert(0) += 1;
            }
            let mut seen: BTreeMap<(&'static str, String, String), usize> = BTreeMap::new();
            for site in &after {
                *seen.entry(key(site)).or_insert(0) += 1;
            }
            let rising: Vec<&Site> = after.iter().filter(|site| seen[&key(site)] > held.get(&key(site)).copied().unwrap_or(0)).collect();
            print(&rising);
        }
        Some("time") => {
            let root = Path::new(&args[1]);
            let mut files = Vec::new();
            walk_tree(root, root, &mut files);
            let started = Instant::now();
            let _ = reference_counts(root, &files);
            let index = started.elapsed();
            let mut per_file: Vec<(Duration, Duration)> = Vec::new();
            for file in &files {
                let Ok(src) = std::fs::read(root.join(file)) else { continue };
                let mut one = Timing { parse: Duration::ZERO, walk: Duration::ZERO };
                let _ = sites_of(file, &src, &mut one);
                per_file.push((one.parse, one.walk));
            }
            let mut walks: Vec<Duration> = per_file.iter().map(|(_, w)| *w).collect();
            walks.sort();
            let parse: Duration = per_file.iter().map(|(p, _)| *p).sum();
            let walk: Duration = walks.iter().sum();
            let pick = |q: f64| walks.get(((walks.len() as f64 - 1.0) * q) as usize).copied().unwrap_or_default();
            println!(
                "files\t{}\tparse_ms\t{:.1}\twalk_ms\t{:.1}\twalk_p50_us\t{}\twalk_p99_us\t{}\twalk_max_us\t{}\tindex_ms\t{:.1}",
                walks.len(),
                parse.as_secs_f64() * 1e3,
                walk.as_secs_f64() * 1e3,
                pick(0.5).as_micros(),
                pick(0.99).as_micros(),
                walks.last().copied().unwrap_or_default().as_micros(),
                index.as_secs_f64() * 1e3
            );
        }
        _ => {
            eprintln!("usage: shapes scan ROOT [FILE...] | shapes new BEFORE AFTER [FILE...] | shapes time ROOT");
            std::process::exit(2);
        }
    }
}
