// @generated by payments-codegen. DO NOT EDIT.
import { postJson } from "../http/client";

export class KlarnaProvider {
  async charge(cents: number): Promise<string> {
    const reply = await postJson("/klarna/orders", { amount: cents });
    return String(reply.id);
  }

  async refund(chargeId: string): Promise<void> {
    await postJson(`/klarna/orders/${chargeId}/refund`, {});
  }
}
