import collections
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent
CORPUS = Path(sys.argv[1] if len(sys.argv) > 1 else '/tmp/klin490-corpus')
KLIN = 'c1805539c4d2743975915ab8452d731bac47e207'
THRESHOLDS = (60, 80, 100, 150)

GENERATED_PATH = re.compile(r'(^|/)(generated|gen|__generated__)(/|$)|\.(gen|generated|pb|g)\.(rs|ts|tsx)$|_generated\.(rs|ts)$')
GENERATED_HEADER = re.compile(r'@generated|do not edit|auto-?generated|generated by', re.I)
IMPORT_LINE = re.compile(r'^\s*(use\s|pub\s+use\s|import\s|export\s+\*\s+from|export\s+\{[^}]*\}\s+from|extern\s+crate|mod\s+\w+;|pub\s+mod\s+\w+;)')
ATTRIBUTE_LINE = re.compile(r'^\s*#!?\[')
TOKEN = re.compile(r'[A-Za-z_$][\w$]*|\d[\w.]*|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`[^`]*`|\S')
TRAIT_IMPL = re.compile(r'^impl\b.*\bfor\b')
TOP_LEVEL = re.compile(r'^(pub(\(\w+\))?\s+)?(impl|fn|struct|enum|trait|mod|const|static|type|async\s+fn|unsafe\s+fn)\b')


def lines_of(span, cache={}):
    key = (span['repo'], span['path'])
    if key not in cache:
        if span['repo'] == 'klin':
            text = subprocess.run(['git', 'show', f'{KLIN}:src/{span["path"]}'], capture_output=True, text=True, check=True).stdout
        else:
            text = (CORPUS / span['repo'] / span['path']).read_text(errors='replace')
        cache[key] = text.splitlines()
    return cache[key]


def generated(span):
    head = '\n'.join(lines_of(span)[:10])
    return bool(GENERATED_PATH.search(span['path']) or GENERATED_HEADER.search(head))


def tokens(text):
    return len(TOKEN.findall(text))


def body_fraction(span):
    region = lines_of(span)[span['start_line'] - 1:span['end_line']]
    total = tokens('\n'.join(region))
    kept, in_import = [], False
    for line in region:
        if in_import:
            in_import = not re.search(r';\s*$|from\s+[\'"]', line)
            continue
        if IMPORT_LINE.match(line):
            in_import = not re.search(r';\s*$|from\s+[\'"]', line)
            continue
        if ATTRIBUTE_LINE.match(line):
            continue
        kept.append(line)
    return tokens('\n'.join(kept)) / total if total else 0


def in_trait_impl(span):
    if span['language'] != 'Rust':
        return False
    for line in reversed(lines_of(span)[:span['start_line']]):
        if TRAIT_IMPL.match(line):
            return True
        if TOP_LEVEL.match(line):
            return False
    return False


def rules(match):
    spans = match['spans']
    return {
        'generated': any(generated(s) for s in spans),
        'import_trim': match['tokens'] * min(body_fraction(s) for s in spans),
        'trait_impl': all(in_trait_impl(s) for s in spans),
    }


def report(matches, labels, keep, title):
    print(f'\n## {title}\n')
    print('| Language | T | Copy / kept pairs | Precision | Copies lost | Non-copy families / kept families |')
    print('|---|---:|---:|---:|---:|---:|')
    for language in ('Rust', 'TypeScript'):
        for t in THRESHOLDS:
            base = [m for m in matches if m['language'] == language and m['tokens'] >= t]
            kept = [m for m in base if keep(m, t)]
            copies = sum(labels[m['id']]['label'] == 'copy' for m in kept)
            lost = sum(labels[m['id']]['label'] == 'copy' for m in base) - copies
            families = collections.defaultdict(set)
            for m in kept:
                families[m['family']].add(labels[m['id']]['label'])
            bad = sum(1 for f in families.values() if f != {'copy'})
            precision = f'{copies / len(kept):.0%}' if kept else 'n/a'
            print(f'| {language} | {t} | {copies} / {len(kept)} | {precision} | {lost} | {bad} / {len(families)} |')


def main():
    data = json.loads((HERE / 'calibration/mapping.json').read_text())['matches']
    labels = json.loads((HERE / 'calibration/labels.json').read_text())
    facts = {m['id']: rules(m) for m in data}
    variants = {
        'No exclusion': lambda m, t: True,
        'E1 generated files': lambda m, t: not facts[m['id']]['generated'],
        'E2 imports and attributes trimmed': lambda m, t: facts[m['id']]['import_trim'] >= t,
        'E3 both spans in Rust trait impls': lambda m, t: not facts[m['id']]['trait_impl'],
        'E1 + E2 + E3': lambda m, t: not facts[m['id']]['generated'] and facts[m['id']]['import_trim'] >= t and not facts[m['id']]['trait_impl'],
    }
    for title, keep in variants.items():
        report(data, labels, keep, title)
    survivors = collections.Counter(
        (m['language'], labels[m['id']]['label'])
        for m in data
        if m['tokens'] >= 60 and not facts[m['id']]['generated'] and facts[m['id']]['import_trim'] >= 60 and not facts[m['id']]['trait_impl']
    )
    print('\nLabels left by E1 + E2 + E3 at T = 60:', dict(survivors))


if __name__ == '__main__':
    main()
