#!/usr/bin/env python3
"""Throwaway prototype for #364. Not klin code.

deps imports ROOT              every import site, with tags and declared status
deps new BEFORE AFTER          new undeclared-import findings (candidate 1)
deps added BEFORE AFTER        new direct dependencies (candidate 3)
deps lockshape ROOT            lockfile entries that fail the shape (candidate 2b)
deps time ROOT                 time to read the imports and manifests of a tree
deps probe BEFORE AFTER        the four candidate columns of one corpus route
"""

import ast
import configparser
import fnmatch
import json
import os
import re
import sys
import time
import tomllib

HERE = os.path.dirname(os.path.abspath(__file__))

SKIP_DIRS = {
    ".git", "node_modules", "vendor", "build", ".build", "dist", "target", "__pycache__",
    ".venv", "venv", "DerivedData", "Pods", "coverage", ".next", "out", "fixtures",
}
TEST_SEGMENTS = {
    "test", "tests", "__tests__", "spec", "specs", "testing", "e2e", "__mocks__", "mocks",
    "testdata", "test_utils", "testutils",
}
EXAMPLE_SEGMENTS = {
    "examples", "example", "docs", "demo", "demos", "benchmarks", "benches", "bench", "scripts",
}
VENDORED_SEGMENTS = {"vendor", "_vendor", "vendored", "third_party", "third-party", "extern"}
GENERATED_MARKERS = ("@generated", "do not edit", "auto-generated", "autogenerated", "code generated")

REMOVED_STDLIB = {
    "asynchat", "asyncore", "distutils", "imp", "smtpd", "lib2to3",
    "aifc", "audioop", "cgi", "cgitb", "chunk", "crypt", "imghdr", "mailcap", "msilib", "nis",
    "nntplib", "ossaudiodev", "pipes", "sndhdr", "spwd", "sunau", "telnetlib", "uu", "xdrlib",
}
STDLIB = set(sys.stdlib_module_names) | REMOVED_STDLIB

PY_EXT = (".py",)
TS_EXT = (".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs")
VARIANTS = ("exact", "table", "prefix")


def norm(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def load_table():
    table = {}
    with open(os.path.join(HERE, "pipreqs-mapping")) as handle:
        for line in handle:
            line = line.strip()
            if ":" in line:
                module, dist = line.split(":", 1)
                table.setdefault(module, set()).add(norm(dist))
    return table


TABLE = load_table()
with open(os.path.join(HERE, "node-builtins.txt")) as handle:
    NODE_BUILTINS = {line.strip() for line in handle if line.strip()}


def walk(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            yield os.path.relpath(full, root).replace(os.sep, "/"), full


def read(full):
    try:
        with open(full, "rb") as handle:
            return handle.read().decode("utf-8", "replace")
    except OSError:
        return ""


def path_tags(rel, text):
    segments = rel.split("/")
    dirs, name = segments[:-1], segments[-1]
    tags = []
    if (any(d in TEST_SEGMENTS for d in dirs) or name.startswith("test_") or name.endswith("_test.py")
            or name == "conftest.py" or ".test." in name or ".spec." in name or ".stories." in name):
        tags.append("test")
    if any(d in EXAMPLE_SEGMENTS for d in dirs):
        tags.append("example")
    if any(d in VENDORED_SEGMENTS for d in dirs):
        tags.append("vendored")
    if (any(m in text[:2048].lower() for m in GENERATED_MARKERS)
            or name.endswith("_pb2.py") or name.endswith("_pb2_grpc.py")):
        tags.append("generated")
    return tags


# ---------------------------------------------------------------- Python manifests

REQ_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def requirement_name(spec):
    spec = spec.strip()
    if not spec or spec.startswith("#"):
        return None
    if spec.startswith("-e ") or spec.startswith("--editable"):
        egg = re.search(r"#egg=([A-Za-z0-9._-]+)", spec)
        return egg.group(1) if egg else None
    if spec.startswith("-") or "://" in spec.split("@")[0]:
        return None
    match = REQ_NAME.match(spec)
    return match.group(1) if match else None


def requirement_is_registry(spec):
    return "@" not in spec.split(";")[0] and "://" not in spec


class PyManifests:
    def __init__(self, root):
        self.root = root
        self.dists = {}
        self.direct = {}
        self.unknown = []
        self.private = False
        self.read_files = set()
        self.files = {rel: full for rel, full in walk(root)}
        for rel, full in self.files.items():
            name = rel.split("/")[-1]
            parent = rel.split("/")[-2] if "/" in rel else ""
            if name == "pyproject.toml":
                self.pyproject(rel, full)
            elif re.fullmatch(r"requirements.*\.txt", name) or (parent == "requirements" and name.endswith((".txt", ".in"))):
                self.requirements(rel, full)
            elif name == "setup.cfg":
                self.setup_cfg(rel, full)
            elif name == "setup.py":
                self.setup_py(rel, full)
            elif name == "Pipfile":
                self.pipfile(rel, full)

    def add(self, name, rel, registry=True):
        if not name or name.lower() == "python":
            return
        self.dists.setdefault(norm(name), rel)
        if registry:
            self.direct.setdefault(norm(name), rel)

    def add_spec(self, spec, rel):
        name = requirement_name(spec)
        if name:
            self.add(name, rel, requirement_is_registry(spec))

    def pyproject(self, rel, full):
        try:
            data = tomllib.loads(read(full))
        except tomllib.TOMLDecodeError:
            self.unknown.append(rel + ": not TOML")
            return
        project = data.get("project", {})
        for spec in project.get("dependencies", []) or []:
            self.add_spec(spec, rel)
        for specs in (project.get("optional-dependencies", {}) or {}).values():
            for spec in specs:
                self.add_spec(spec, rel)
        for specs in (data.get("dependency-groups", {}) or {}).values():
            for spec in specs:
                if isinstance(spec, str):
                    self.add_spec(spec, rel)
        for spec in data.get("build-system", {}).get("requires", []) or []:
            self.add_spec(spec, rel)
        tool = data.get("tool", {})
        poetry = tool.get("poetry", {})
        tables = [poetry.get("dependencies", {}), poetry.get("dev-dependencies", {})]
        tables += [group.get("dependencies", {}) for group in (poetry.get("group", {}) or {}).values()]
        for table in tables:
            for name, value in (table or {}).items():
                registry = not (isinstance(value, dict) and ("path" in value or "git" in value or "url" in value))
                self.add(name, rel, registry)
        for spec in tool.get("uv", {}).get("dev-dependencies", []) or []:
            self.add_spec(spec, rel)
        for specs in (tool.get("pdm", {}).get("dev-dependencies", {}) or {}).values():
            for spec in specs:
                self.add_spec(spec, rel)
        if "dependencies" in (project.get("dynamic", []) or []):
            dynamic = tool.get("setuptools", {}).get("dynamic", {}).get("dependencies", {})
            files = dynamic.get("file", []) if isinstance(dynamic, dict) else []
            files = [files] if isinstance(files, str) else files
            base = os.path.dirname(rel)
            readable = files and all(re.fullmatch(r"requirements.*\.txt", os.path.basename(f)) for f in files)
            if not readable:
                self.unknown.append(rel + ": dynamic dependencies")
            for f in files:
                self.requirements(os.path.normpath(os.path.join(base, f)), os.path.join(self.root, base, f))
        if tool.get("uv", {}).get("index") or tool.get("poetry", {}).get("source") or tool.get("pdm", {}).get("source"):
            self.private = True

    def requirements(self, rel, full):
        if rel in self.read_files or not os.path.isfile(full):
            return
        self.read_files.add(rel)
        for line in read(full).splitlines():
            line = line.split(" #")[0].strip()
            if re.match(r"^(-r|-c|--requirement|--constraint)\s*", line):
                target = re.sub(r"^(-r|-c|--requirement|--constraint)\s*=?\s*", "", line)
                base = os.path.dirname(rel)
                self.requirements(os.path.normpath(os.path.join(base, target)), os.path.join(self.root, base, target))
            elif re.match(r"^(-i|--index-url|--extra-index-url)\b", line):
                self.private = True
            else:
                self.add_spec(line, rel)

    def setup_cfg(self, rel, full):
        parser = configparser.ConfigParser(interpolation=None)
        try:
            parser.read_string(read(full))
        except configparser.Error:
            self.unknown.append(rel + ": not INI")
            return
        if parser.has_option("options", "install_requires"):
            for line in parser.get("options", "install_requires").splitlines():
                self.add_spec(line, rel)
        if parser.has_section("options.extras_require"):
            for _, value in parser.items("options.extras_require"):
                for line in value.splitlines():
                    self.add_spec(line, rel)

    def setup_py(self, rel, full):
        try:
            tree = ast.parse(read(full))
        except SyntaxError:
            self.unknown.append(rel + ": not Python")
            return
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            for keyword in node.keywords:
                if keyword.arg not in ("install_requires", "extras_require", "tests_require"):
                    continue
                lists = [keyword.value]
                if keyword.arg == "extras_require":
                    lists = keyword.value.values if isinstance(keyword.value, ast.Dict) else [None]
                for value in lists:
                    if isinstance(value, (ast.List, ast.Tuple)) and all(
                            isinstance(e, ast.Constant) and isinstance(e.value, str) for e in value.elts):
                        for element in value.elts:
                            self.add_spec(element.value, rel)
                    else:
                        self.unknown.append(rel + ": " + keyword.arg + " is not a literal list")

    def pipfile(self, rel, full):
        try:
            data = tomllib.loads(read(full))
        except tomllib.TOMLDecodeError:
            self.unknown.append(rel + ": not TOML")
            return
        for table in ("packages", "dev-packages"):
            for name, value in (data.get(table, {}) or {}).items():
                registry = not (isinstance(value, dict) and ("path" in value or "git" in value))
                self.add(name, rel, registry)

    def declares(self, module, variant):
        key = norm(module)
        if key in self.dists:
            return True
        if variant in ("table", "prefix") and any(d in self.dists for d in TABLE.get(module, ())):
            return True
        if variant == "prefix" and any(d.startswith(key + "-") for d in self.dists):
            return True
        return False


# ---------------------------------------------------------------- Python imports

IMPORT_ERRORS = {"ImportError", "ModuleNotFoundError", "Exception", "BaseException"}
PLATFORM_TEXT = ("sys.platform", "os.name", "platform.system", "sys.version_info")


def handler_names(handler):
    if handler.type is None:
        return {"Exception"}
    nodes = handler.type.elts if isinstance(handler.type, ast.Tuple) else [handler.type]
    return {n.id if isinstance(n, ast.Name) else n.attr if isinstance(n, ast.Attribute) else "" for n in nodes}


def py_sites(rel, text):
    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError):
        return None
    sites = []

    def visit(node, tags):
        if isinstance(node, ast.Import):
            for alias in node.names:
                sites.append((alias.name.split(".")[0], node.lineno, sorted(tags)))
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:
                sites.append((node.module.split(".")[0], node.lineno, sorted(tags)))
        if isinstance(node, ast.Try) or (hasattr(ast, "TryStar") and isinstance(node, ast.TryStar)):
            guarded = any(handler_names(h) & IMPORT_ERRORS for h in node.handlers)
            for child in node.body:
                visit(child, tags | ({"guarded"} if guarded else set()))
            for child in node.handlers + node.orelse + node.finalbody:
                visit(child, tags)
            return
        if isinstance(node, ast.If):
            test = ast.unparse(node.test)
            if re.fullmatch(r"(typing\.)?TYPE_CHECKING", test.strip()):
                for child in node.body:
                    visit(child, tags | {"type-only"})
                for child in node.orelse:
                    visit(child, tags)
                return
            if any(p in test for p in PLATFORM_TEXT):
                for child in node.body + node.orelse:
                    visit(child, tags | {"platform"})
                return
        for child in ast.iter_child_nodes(node):
            visit(child, tags)

    visit(tree, set())
    return sites


def local_modules(root):
    names = set()
    for rel, full in walk(root):
        parts = rel.split("/")
        stem, ext = os.path.splitext(parts[-1])
        if ext in (".py", ".pyi", ".pyx", ".so"):
            names.add(stem.split(".")[0])
            if ext == ".py" and len(parts) > 1:
                names.add(parts[-2])
    return names


# ---------------------------------------------------------------- TypeScript imports

def strip_comments(text):
    out = []
    i, n = 0, len(text)
    quote = None
    while i < n:
        c = text[i]
        if quote:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == quote:
                quote = None
            i += 1
            continue
        if c in "'\"`":
            quote = c
            out.append(c)
            i += 1
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            end = n if j < 0 else j + 2
            out.append("\n" * text.count("\n", i, end))
            i = end
        else:
            out.append(c)
            i += 1
    return "".join(out)


TS_PATTERNS = [
    re.compile(r"(?<![.\w$])import\s+(type\s+)?[\w*{}\s,$]*?\bfrom\s*(['\"])([^'\"\n]+)\2", re.S),
    re.compile(r"(?<![.\w$])export\s+(type\s+)?[\w*{}\s,$]*?\bfrom\s*(['\"])([^'\"\n]+)\2", re.S),
    re.compile(r"(?<![.\w$])import\s*()(['\"])([^'\"\n]+)\2"),
    re.compile(r"(?<![.\w$])import\s*\(\s*()(['\"])([^'\"\n]+)\2\s*\)"),
    re.compile(r"(?<![.\w$])require\s*\(\s*()(['\"])([^'\"\n]+)\2\s*\)"),
]


def ts_sites(text):
    stripped = strip_comments(text)
    seen = set()
    sites = []
    for pattern in TS_PATTERNS:
        for match in pattern.finditer(stripped):
            start = match.start(3)
            if start in seen:
                continue
            seen.add(start)
            line = stripped.count("\n", 0, start) + 1
            tags = ["type-only"] if match.group(1) else []
            sites.append((match.group(3), line, tags))
    return sorted(sites, key=lambda s: s[1])


def jsonc(text):
    text = strip_comments(text)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


class TsManifests:
    def __init__(self, root):
        self.declared = {}
        self.direct = {}
        self.members = set()
        self.aliases = []
        self.private_scopes = set()
        self.private_all = False
        for rel, full in walk(root):
            name = rel.split("/")[-1]
            if name == "package.json":
                try:
                    data = json.loads(read(full))
                except ValueError:
                    continue
                if not isinstance(data, dict):
                    continue
                if isinstance(data.get("name"), str):
                    self.declared.setdefault(data["name"], rel)
                    self.members.add(data["name"])
                for table in ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies"):
                    for dep, spec in (data.get(table) or {}).items():
                        self.declared.setdefault(dep, rel)
                        if not isinstance(spec, str):
                            continue
                        alias = re.match(r"npm:((?:@[^/@]+/)?[^@]+)", spec)
                        if alias:
                            self.direct.setdefault(alias.group(1), rel)
                        elif not re.match(r"(workspace:|file:|link:|portal:|git|github:|https?:|[\w-]+/[\w.-]+$)", spec):
                            self.direct.setdefault(dep, rel)
            elif re.fullmatch(r"(tsconfig.*|jsconfig)\.json", name):
                try:
                    data = jsonc(read(full))
                except ValueError:
                    continue
                paths = (data.get("compilerOptions") or {}).get("paths") or {}
                self.aliases.extend(paths.keys())
            elif name == ".npmrc":
                for line in read(full).splitlines():
                    match = re.match(r"\s*(@[\w.-]+:)?registry\s*=\s*(\S+)", line)
                    if match and "registry.npmjs.org" not in match.group(2) and "registry.yarnpkg.com" not in match.group(2):
                        if match.group(1):
                            self.private_scopes.add(match.group(1)[:-1])
                        else:
                            self.private_all = True

    def package(self, spec):
        parts = spec.split("/")
        return "/".join(parts[:2]) if spec.startswith("@") else parts[0]

    def judged(self, spec):
        if spec.startswith((".", "/", "#", "$", "~")) or re.match(r"^[a-zA-Z][\w+.-]*:", spec):
            return False
        if spec in NODE_BUILTINS or spec.split("/")[0] in NODE_BUILTINS:
            return False
        if any(fnmatch.fnmatchcase(spec, alias) for alias in self.aliases):
            return False
        return True

    def declares(self, package):
        if package in self.declared:
            return True
        types = "@types/" + (package[1:].replace("/", "__") if package.startswith("@") else package)
        return types in self.declared

    def is_private(self, package):
        return self.private_all or (package.startswith("@") and package.split("/")[0] in self.private_scopes)


# ---------------------------------------------------------------- candidate 1

class Tree:
    def __init__(self, root):
        self.root = root
        self.py = PyManifests(root)
        self.ts = TsManifests(root)
        self.local = local_modules(root)
        self.parse_errors = []
        self.sites = []
        for rel, full in walk(root):
            if rel.endswith(PY_EXT):
                text = read(full)
                found = py_sites(rel, text)
                if found is None:
                    self.parse_errors.append(rel)
                    continue
                tags = path_tags(rel, text)
                for module, line, site_tags in found:
                    if module in STDLIB or module in self.local or module == "__future__":
                        continue
                    self.sites.append(("python", module, rel, line, sorted(set(tags + site_tags))))
            elif rel.endswith(TS_EXT) and not rel.endswith(".min.js"):
                text = read(full)
                tags = path_tags(rel, text)
                for spec, line, site_tags in ts_sites(text):
                    if not self.ts.judged(spec):
                        continue
                    self.sites.append(("ts", self.ts.package(spec), rel, line, sorted(set(tags + site_tags))))

    def declared(self, lang, identity, variant):
        if lang == "python":
            return self.py.declares(identity, variant)
        return self.ts.declares(identity)

    def undeclared(self, variant):
        out = {}
        for lang, identity, rel, line, tags in self.sites:
            if lang == "python" and self.py.unknown:
                continue
            if not self.declared(lang, identity, variant):
                out.setdefault((lang, identity), []).append((rel, line, tags))
        return out


def cmd_imports(root):
    tree = Tree(root)
    for lang, identity, rel, line, tags in tree.sites:
        status = ",".join(v for v in VARIANTS if not tree.declared(lang, identity, v)) or "declared"
        print(f"{lang}\t{identity}\t{rel}:{line}\t{','.join(tags) or '-'}\t{status}")
    for item in tree.py.unknown:
        print(f"python\t-\t{item}\t-\tunknown")


def cmd_new(before_root, after_root):
    before, after = Tree(before_root), Tree(after_root)
    if after.py.unknown:
        print(f"python\t*\t-\t-\tunknown\t{'; '.join(after.py.unknown)}")
    for variant in VARIANTS:
        old = before.undeclared(variant)
        old_untagged = {key for key, sites in old.items() if any(not tags for _, _, tags in sites)}
        for key, sites in sorted(after.undeclared(variant).items()):
            lang, identity = key
            if lang == "ts" and variant != "exact":
                continue
            untagged = [s for s in sites if not s[2]]
            if key in old_untagged:
                continue
            if untagged:
                rel, line, _ = untagged[0]
                print(f"{lang}\t{variant}\t{identity}\t{rel}:{line}\tfinding\t-")
            elif key not in old:
                rel, line, tags = sites[0]
                every = sorted({t for s in sites for t in s[2]})
                print(f"{lang}\t{variant}\t{identity}\t{rel}:{line}\texcluded\t{','.join(every)}")


# ---------------------------------------------------------------- candidate 3

def cargo_direct(root):
    out = {}
    for rel, full in walk(root):
        if not rel.endswith("Cargo.toml") or rel.split("/")[-1] != "Cargo.toml":
            continue
        try:
            data = tomllib.loads(read(full))
        except tomllib.TOMLDecodeError:
            continue

        def tables(node, path):
            if isinstance(node, dict):
                for key, value in node.items():
                    if key in ("dependencies", "dev-dependencies", "build-dependencies") and isinstance(value, dict):
                        yield value
                    elif isinstance(value, dict):
                        yield from tables(value, path + [key])

        for table in tables(data, []):
            for name, value in table.items():
                if isinstance(value, dict):
                    if "path" in value or "git" in value or value.get("workspace") is True:
                        continue
                    name = value.get("package", name)
                    if "registry" in value:
                        out.setdefault(name, (rel, True))
                        continue
                out.setdefault(name, (rel, False))
    return out


def go_direct(root):
    out = {}
    for rel, full in walk(root):
        if rel.split("/")[-1] != "go.mod":
            continue
        text = read(full)
        local = set(re.findall(r"^\s*(?:replace\s+)?(\S+)(?:\s+\S+)?\s+=>\s+\.{1,2}/", text, re.M))
        private = bool(re.search(r"GOPRIVATE", text))
        block = False
        for line in text.splitlines():
            line = line.split("//")[0].strip()
            if line.startswith("require ("):
                block = True
                continue
            if block and line == ")":
                block = False
                continue
            match = re.match(r"^require\s+(\S+)\s+\S+", line) or (block and re.match(r"^(\S+)\s+v\S+", line))
            if match and match.group(1) not in local:
                out.setdefault(match.group(1), (rel, private))
    return out


def go_private_patterns(root):
    patterns = []
    for rel, full in walk(root):
        name = rel.split("/")[-1]
        if name in (".env", "Makefile") or rel.startswith(".github/workflows/") or name.endswith((".gitlab-ci.yml",)):
            patterns += re.findall(r"GOPRIVATE[=:]\s*['\"]?([^\s'\"]+)", read(full))
    return [p for group in patterns for p in group.split(",")]


def direct_deps(root):
    py = PyManifests(root)
    ts = TsManifests(root)
    go_patterns = go_private_patterns(root)
    deps = {}
    for name, rel in py.direct.items():
        deps[("pypi", name)] = (rel, py.private)
    for name, rel in ts.direct.items():
        if name not in ts.members:
            deps[("npm", name)] = (rel, ts.is_private(name))
    for name, (rel, private) in cargo_direct(root).items():
        deps[("crates", name)] = (rel, private)
    for name, (rel, _) in go_direct(root).items():
        private = any(fnmatch.fnmatchcase(name, p) or name.startswith(p.rstrip("/*") + "/") for p in go_patterns)
        deps[("go", name)] = (rel, private)
    return deps


def cmd_added(before_root, after_root):
    before, after = direct_deps(before_root), direct_deps(after_root)
    for (ecosystem, name), (rel, private) in sorted(after.items()):
        if (ecosystem, name) not in before:
            print(f"{ecosystem}\t{name}\t{rel}\t{'private' if private else 'public'}")


# ---------------------------------------------------------------- candidate 2b

NPM_INTEGRITY = re.compile(r"^(sha512-[A-Za-z0-9+/]{86}==|sha1-[A-Za-z0-9+/]{27}=)$")
CARGO_CHECKSUM = re.compile(r"^[0-9a-f]{64}$")
GO_HASH = re.compile(r"^h1:[A-Za-z0-9+/]{43}=$")


def npm_entry_problem(entry):
    resolved = entry.get("resolved")
    if resolved is None:
        return "no resolved"
    if not resolved.startswith("https://"):
        return None
    integrity = entry.get("integrity")
    if integrity is None:
        return "no integrity"
    if not any(NPM_INTEGRITY.match(token) for token in integrity.split()):
        return "malformed integrity"
    return None


def npm_v1(tree, prefix, out, rel):
    for name, entry in (tree or {}).items():
        if not isinstance(entry, dict):
            continue
        version = str(entry.get("version", ""))
        if not (entry.get("bundled") or version.startswith(("file:", "git", "link:")) or "://" in version and not version.startswith("https")):
            problem = npm_entry_problem(entry)
            if problem:
                out.append((rel, prefix + name, problem))
        npm_v1(entry.get("dependencies"), prefix + name + ">", out, rel)


def cargo_members(root):
    names = set()
    for rel, full in walk(root):
        if rel.split("/")[-1] == "Cargo.toml":
            try:
                names.add(tomllib.loads(read(full)).get("package", {}).get("name"))
            except tomllib.TOMLDecodeError:
                pass
    return names


def lockshape(root):
    members = None
    out = []
    counts = {"npm": 0, "cargo": 0, "go": 0}
    for rel, full in walk(root):
        name = rel.split("/")[-1]
        if name == "package-lock.json":
            try:
                data = json.loads(read(full))
            except ValueError:
                out.append((rel, "-", "not JSON"))
                continue
            packages = data.get("packages")
            if isinstance(packages, dict):
                for key, entry in packages.items():
                    if key == "" or "node_modules/" not in key or entry.get("link") or entry.get("inBundle"):
                        continue
                    counts["npm"] += 1
                    problem = npm_entry_problem(entry)
                    if problem:
                        out.append((rel, key, problem))
            else:
                npm_v1(data.get("dependencies"), "", out, rel)
                counts["npm"] += len(data.get("dependencies") or {})
        elif name == "Cargo.lock":
            try:
                data = tomllib.loads(read(full))
            except tomllib.TOMLDecodeError:
                out.append((rel, "-", "not TOML"))
                continue
            metadata = data.get("metadata", {}) or {}
            members = members or cargo_members(root)
            for package in data.get("package", []) or []:
                source = package.get("source")
                if (source or "").startswith("git+") or (not source and package.get("name") in members):
                    continue
                counts["cargo"] += 1
                if not source:
                    out.append((rel, f"{package.get('name')} {package.get('version')}", "no source"))
                    continue
                checksum = package.get("checksum") or metadata.get(
                    f"checksum {package.get('name')} {package.get('version')} ({source})")
                if checksum is None:
                    out.append((rel, f"{package.get('name')} {package.get('version')}", "no checksum"))
                elif not CARGO_CHECKSUM.match(checksum):
                    out.append((rel, f"{package.get('name')} {package.get('version')}", "malformed checksum"))
        elif name == "go.sum":
            for number, line in enumerate(read(full).splitlines(), 1):
                fields = line.split()
                if not fields:
                    continue
                counts["go"] += 1
                if len(fields) != 3 or not GO_HASH.match(fields[2]):
                    out.append((rel, f"line {number}", "malformed hash"))
    return out, counts


def cmd_lockshape(root):
    out, counts = lockshape(root)
    for rel, key, problem in out:
        print(f"{rel}\t{key}\t{problem}")
    print(f"entries\tnpm={counts['npm']}\tcargo={counts['cargo']}\tgo={counts['go']}", file=sys.stderr)


def cmd_time(root):
    started = time.perf_counter()
    tree = Tree(root)
    elapsed = time.perf_counter() - started
    files = sum(1 for rel, _ in walk(root) if rel.endswith(PY_EXT + TS_EXT))
    print(f"files\t{files}\tsites\t{len(tree.sites)}\tseconds\t{elapsed:.3f}")


def new_findings(before_root, after_root):
    before, after = Tree(before_root), Tree(after_root)
    found, excluded = {}, {}
    for variant in VARIANTS:
        old = before.undeclared(variant)
        old_untagged = {key for key, sites in old.items() if any(not tags for _, _, tags in sites)}
        for key, sites in sorted(after.undeclared(variant).items()):
            if key in old_untagged or (key[0] == "ts" and variant != "exact"):
                continue
            if any(not tags for _, _, tags in sites):
                found.setdefault(key, []).append(variant)
            elif key not in old:
                excluded[key] = sorted({t for s in sites for t in s[2]})
    return found, excluded, after.py.unknown


def cmd_probe(before_root, after_root):
    import registry
    found, excluded, unknown = new_findings(before_root, after_root)
    c1 = [f"{name}[{','.join(v)}]" if lang == "python" else name for (lang, name), v in sorted(found.items())]
    c1 += [f"{name}({','.join(tags)})" for (_, name), tags in sorted(excluded.items())]
    c1 += ["unknown"] if unknown else []
    base_shape = {(rel, key) for rel, key, _ in lockshape(before_root)[0]}
    c2 = [f"{key}({problem})" for rel, key, problem in lockshape(after_root)[0] if (rel, key) not in base_shape]
    before, after = direct_deps(before_root), direct_deps(after_root)
    added = [(eco, name, private) for (eco, name), (_, private) in sorted(after.items()) if (eco, name) not in before]
    rows = registry.load()
    c3 = [f"{eco}:{name}" for eco, name, _ in added]
    c4 = [f"{name}=private" if private else f"{name}={registry.lookup(eco, name, rows)[0]}" for eco, name, private in added]
    print("\t".join(" ".join(c) or "-" for c in (c1, c2, c3, c4)))


def main(argv):
    commands = {
        "imports": (cmd_imports, 1), "new": (cmd_new, 2), "added": (cmd_added, 2),
        "lockshape": (cmd_lockshape, 1), "time": (cmd_time, 1), "probe": (cmd_probe, 2),
    }
    if len(argv) < 2 or argv[1] not in commands or len(argv) - 2 != commands[argv[1]][1]:
        sys.exit(__doc__)
    command, _ = commands[argv[1]]
    command(*argv[2:])


if __name__ == "__main__":
    main(sys.argv)
